### PR TITLE
upgrade angular & bazel rules

### PR DESCRIPTION
**Pull request by juristr**
Upgrade to angular `v6.0.0-rc.1` (upgrading to RC2 or RC3 failed during bazel build -> `npm run build`).

The build seems to run, however I noticed that it doesn't produce the usual `main`, `module`, `esm5` etc entries in the `package.json`.

On the official RC release of [Angular however they are correctly listed](https://unpkg.com/@angular/core@6.0.0-rc.1/package.json). Are they supposed to be added manually now?

Currently I'm trying to integrate a [demo app following your example](https://github.com/alexeagle/angular-bazel-example).

### CODE REVIEW

**Comment by alexeagle** [comment]
there's a warning:
```
WARNING: no module metadata for package ngx-tabs-libdemo
   Not updating the package.json file to point to it
```
I now expect a `module_name` attribute on the `ng_module` that appears in `deps` of `ng_package` to know what the package name should be and produce the flat module metadata.

**Comment by alexeagle** [comment]
I'll push another commit to this branch that also updates to latest RC

**Comment by juristr** [comment]
> there's a warning:

Oh, totally overlooked that.

But just verified and your last commit fixes it 👍. Thx a lot for being so responsive to my dummy questions 😄. Really appreciate it.

Btw, is there an option in bazel to tell it to place the output (like in this case the npm distributable files) into a folder - like `dist` of the current bazel workspace?

I searched [on the docs](https://docs.bazel.build/versions/master/output_directories.html) and found things like `--output_base` but it's not exactly that.

**Comment by alexeagle** [comment]
Bazel will never be willing to put outputs in your input tree. The
`--symlink_prefix` flag can be used to do that, e.g.
`--symlink_prefix=dist/` but I prefer to ask a different question - why do
you want to locate the output? Is it to pass it to some other tool? In that
case, maybe that other tool would be better hosted inside bazel, so it gets
updated artifacts when it runs. For example, the `npm_package` and
`ng_package` rules have a `.pack` and `.publish` verb so you can publish
directly in Bazel - that's what we do for angular:
https://github.com/angular/angular/pull/23097/files#diff-df86c040dc90c2a1dd403c9191584e45R10

**Comment by alexeagle** [comment]
Each build command does print the output location, so when you `bazel build
:npm_package` it prints the path to it, which you can predict as $(bazel
info bazel-bin)/npm_package

**Pull request merged**
